- src/parsers/command-mssql.lisp
Added missing #+sbcl for sb-ext:*muffled-warnings*.  prevented succesfully building the application with ccl
> add missing conditional compilation for sbcl

- INSTALL.md
Otherwise cffi tries to load the 64-bit version of the library which fails
> add note to install universal binaries of freetds

- src/parsers/command-db-uri.lisp
Fix issue #168 by adding . in the punct defrule.
> Allow dots in user names

- pgloader.spec
RPM complains about these dates being invalid during the build process.
I'm not sure which date exactly you mean, but I've changed the name of the day to match the number so the RPM can be built without errors.
> Fix incorrect dates in specfile

- web/src/mysql.md
- web/src/sqlite.md
Hi Dimitri,
I think I found 2 typos in the fantastic PgLoader web documentation. Hope you are fine and to see you soon in one of your Postgresql talk ;-)
> Fix explanation typo. Drop table if it exists

- Makefile
It may have taken me a year, but [pgloader is finally in Homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pgloader.rb)!
This PR brings a couple updates to the `pgloader-standalone` target to bring it in line with updates to the `pgloader` target. Things seem to work without this update, but I didn't test the SSL mess that `hooks.lisp` is supposed to address. (I know this dual-target Makefile is far from ideal, but I can't think of a better solution.)
> Match pgloader-standalone target to pgloader target

- bootstrap-centos7.sh
This corrects the bootstrap for CentOS 7.
Notes:
- During installation you still need to do the following:
```sh
sudo yum -y install freetds
sudo ln -s /usr/lib64/libsybdb.so.5 /usr/lib64/libsybdb.so
```
I'm not sure which package depends on `libsybdb.so` to fix that.
- `--compress-core` is not available in the `sbcl` from epel. So I build the RPM with `make COMPRESS_CORE=no rpm`
> Adds bootstrap for CentOS 7

- src/pgsql/queries.lisp
- src/sources/mysql/mysql.lisp
* Fix identifier case in FOREIGN KEY constraints
* Fix string delimiter syntax in COMMENT statements
> Two bugfixes

- src/sources/mysql/mysql-cast-rules.lisp
> Default cast rules for MySQL's datatime types fixed

- INSTALL.md
- Makefile
- README.md
Fedora 22 (quite new), Ubuntu 12.04 (old, but LTS), and perhaps other Linux distributions, compile SBCL without core-compression.
[As mentioned](https://github.com/dimitri/pgloader/issues/58#issuecomment-43108976), it would be helpful if the `Makefile` could detect core-compression if available, as opposed to asking users to manually use `make COMPRESS_CORE=no`.
This PR is an attempt at detection.  If it is acceptable, I'll modify the `README.md` as well, before this is merged.
(I also made a few small changes re-organizing the `Makefile` which I can remove, if they are not desired.)
Linux without core-compression:
```
;; loading system "pgloader"
;; loading file #P"/home/rmichael/source/pgloader/src/hooks.lisp"
[undoing binding stack and other enclosing state... done]
[saving current …
```
> Detect sbcl core compression and Makefile gardening.

- src/sources/mysql/mysql-cast-rules.lisp
if you have function or operator with  type which is removed, you will have error
error: cannot drop type because other objects depend on it
> fix type drop to cascade

- pgloader.1.md
- src/parsers/command-cast-rules.lisp
- src/sources/common/casting-rules.lisp
Use case: Django dissuades setting `NULL` on text fields “on string-based fields […] because empty string values will always be stored as empty strings, not as `NULL`. If a string-based field has null=True, that means it has two possible values for »no data«: `NULL`, and the empty string. In most cases, it’s redundant to have two possible values for »no data«; the Django convention is to use the empty string, not `NULL`.”.
pgloader already supports custom transformations which can be used to replace `NULL` values in string-based columns with empty strings. Setting `NOT NULL` constraint on those columns could possibly be achieved by running a database query to extract their names and then generating relevant `ALTER TABLE` statements, but a cast option in pgloader is a more convenient way. …
> Add the “set not null” cast option for MySQL

- src/package.lisp
Defining rules on standard symbols like ``cl:namestring`` is a bad idea since other systems may do the same, inadvertently overwriting each other's rules.
Furthermore, future esrap versions will probably prevent defining rules whose names are symbols in locked packages, making this change mandatory.
> Shadow symbols NAMESTRING, NUMBER and INLINE in pgloader.parser package

- src/params.lisp
Fix spelling error for uiop:make-pathname* key by changing :direction to :directory
Fixes Issue #544
> Fix Windows build support

- src/sources/mssql/mssql-cast-rules.lisp
If a custom CAST rule is defined (e.g CAST type varchar to varchar) the
original typemod get's lost. This commit is based on Dimitris patch from
571 and adds typmod support for "char", "nchar", "varchar", "nvarchar"
and "binary".
> MSSQL: Add support for typemods of various text types

- src/sources/mssql/mssql-cast-rules.lisp
The previous commit makes it possible to convert typemods for various
text types. In MSSQL it's possible to create a column like varchar(max).
Internally this is reported as varchar(-1) which results in a CREATE
TABLE statement that contains e.g. varchar(-1).
This patch drops the typemod if it's -1 (max).
It's based on Dimitris patch slightly modified by myself.
> MSSQL: fix typmod conversion for "max" typemods

- .travis.sh
- .travis.yml
Sets up one job for each combination of Lisp and PostgreSQL we want to test. I tried adding `PGVERSION=10` as discussed in https://github.com/dimitri/pgloader/pull/574#issuecomment-307563027, but there's no `postgresql-10-ip4r` package in the PGDG repositories, yet.
I added a commit that uses `ccl` even though the tests are failing. We can omit it if you like.
> Multiple Travis CI jobs

- src/sources/mssql/mssql-schema.lisp
Currently the default value getdate() is replaced by 'now' which creates
statements like:
CREATE TABLE ... created timestamp 'now' ...
which leads to table definitions like:
default '2017-06-12 17:54:04.890129'::timestamp without time zone
This is because 'now' is evaluated when creating the table.
This commit fixes the issue by using CURRENT_TIMESTAMP as default
instead of 'now'.
> MSSQL: Fix Default value translation for getdate() (#576)

- src/sources/mssql/mssql-schema.lisp
The former query to find foreign key constraints doesn't consider ON
UPDATE and ON DELETE rules.
> MSSQL: Add ON UPDATE / DELETE support for fkeys

- README.md
If you run 
```
brew install --head pgloader
```
the brew will error out with the message
```
Error: Specify `--HEAD` in uppercase to build from trunk.
```
> Fix the brew install command in README

- src/utils/transforms.lisp
I've tested this on one of my import jobs and can confirm that the rows containing a `NULL` `binary(n)` value are preserved.
> Ignore nulls in varbinary-to-string transform

- src/sources/mysql/sql/list-all-indexes.sql
The suspected fix for #632, confirmed to work in my test environment against the `mysql:latest` docker image.
> Add missing column to GROUP BY.

- docs/tutorial/csv.rst
- docs/tutorial/dBase.rst
- docs/tutorial/fixed.rst
- docs/tutorial/sqlite.rst
They are still in Markdown format, remove or move to rst.
> doc: fix a few link format

- docs/pgloader.rst
The default logfile location seems to be `/tmp/pgloader/pgloader.log`, not `/tmp/pgloader.log` as currently documented. This is observable in practice and also in [the source code](https://github.com/dimitri/pgloader/blob/5b227200a9525050ce60e44e2bc899a3c2b1f018/src/main.lisp#L110).
> Fix minor error in docs about logfile location

- docs/ref/mysql.rst
When reading http://pgloader.readthedocs.io/en/latest/ref/mysql.html I came across the section of binary. On the documentation the indentation is off and is kinda hard to read :)
> Correct binary datatype changes

- .dockerignore
- Dockerfile
- Dockerfile.ccl
Reduced size of the docker images by using smaller base image and multistage builds:
```
dimitri/pgloader   latest       452MB
pgloader           latest       171MB
dimitri/pgloader   ccl.latest   730MB
pgloader           ccl.latest   248MB
```
Also reduced layer count of the images.
We could save even more space by installing as few packages as possible. You don't need `make` etc. in the final container. Installing less packages inside the builder container could also improve build time.
I think the package requirements in README are outdated. Some packages are missing and some others are only required during compilation.
> Improved Dockerfiles/docker image size

- src/monkey/mssql.lisp
syb-real is a 4 byte float, which seems to correspond exactly to the lisp type float
> Fix pgloader bug #844 by adding support for mssql real types

- README.md
Adds instructions for building Docker images using SBCL or CCL.
I encountered issues building the standard SBCL Dockerfile, possibly related to #832. It wasn't readily apparent that there was a ccl option for the Docker build. This should draw users' attention to this option.
> Add Docker build instructions

- Dockerfile
- Dockerfile.ccl
I had some issues building using the supplied Dockerfiles (I tried the CCL version only, in this case) that were resolved by adding two packages from apt: cl-ironclad and cl-babel. Contributing back the changes here.
> add cl-ironclad and cl-babel dependencies to docker builds

- src/parsers/command-mssql.lisp
With this change, preserve index names is also supported for MSSQL-connections.
> Allow "preserve index names" for MSSQL

- src/pgsql/connection.lisp
The regex used in parse-postgresql-version-string failed to handle
"PostgreSQL 10.6, compiled by Visual C++ build 1800, 64-bit"
correctly.
> Correctly parse PostgreSQL version string on Windows.

- docs/ref/mysql.rst
It seems like `create schema` option for WITH statement is invalid.
> Remove invalid WITH default option

- Dockerfile.ccl
pgloader:ccl.latest throws an error: Shared library not open: "libssl.so.1.1". This commit adds libssl1.1 to the docker image which fixes the issue.
> Fix ccl docker images not having libssl

- Makefile
Fixes #1090.
@gjvoosten Please check if this resolves the build issue. Works on my machine, maybe it'll work on yours as well.
> Do not reload pgloader in Makefile

- src/sources/mysql/mysql-schema.lisp
Fix: https://github.com/dimitri/pgloader/issues/1029
This PR use the st_astext function instead of astext that has been removed since mysql 8+
For info: ST_ASTEXT is available since mysql 5.6+ ([link](https://dev.mysql.com/doc/refman/5.6/en/gis-format-conversion-functions.html#function_st-astext))
> fix(mysql): use new st_astext function

- Makefile
#1092 requires us to switch to a new Quicklisp distribution in order to bump CFFI to version 0.21.0. This commit switches to the newest available QL dist (2020-02-18) to achieve this.
> Update Quicklisp dist to 2020-02-18

- src/monkey/mssql.lisp
- src/sources/mssql/mssql-cast-rules.lisp
- src/sources/mssql/mssql-schema.lisp
To solve #976 (as far as I tested)
Beware of CONVERT(varchar...). In mssql, the varchar default size is 30 in a cast.
Good practice is to dimension it explicitely. Not enough here for datetimeoffset (cast to 32 chars) so the varchar size needs to be explicitely set.
> handling mssql datetimeoffset

- .travis.yml
We remove the Travis jobs without the `PGLOADER` environment variable set (to try and fix #1109) and add Postgres versions 10, 11, and 12 to build and test pgloader against them (to try and fix #1108).
Please merge only if [the related Travis job](https://travis-ci.org/github/dimitri/pgloader/builds/666266112) succeeds.
> Change Travis build matrix

- .travis.sh
- .travis.yml
Fixes #1111.
We remove unnecessary .travis.sh code for removing old Postgres versions.
> Simplify and fix errors/warnings/notes on Travis configuration

- pgloader.spec
> Update pgloader.spec for 3.6.2 release

- src/load/copy-data.lisp
- src/load/migrate-database.lisp
- src/package.lisp
- src/sources/common/api.lisp
- src/sources/mysql/mysql-schema.lisp
- src/sources/mysql/mysql.lisp
- src/sources/mysql/sql/list-table-rows.sql
- src/utils/catalog.lisp
This should help optimize the duration of migrating databases with very big
tables and lots of smaller ones. It might be a little too naive as far as
the optimisation goes, while still being an improvement on the default
alphabetical one.
Fixes #1099.
> Implement tables row count ordering for MySQL.

- src/sources/mysql/sql/list-table-rows.sql
Since `pgloader` @ 11970bbc, importing from MySQL 5.7 to Postgresql 11
with SSL triggers the following exception:
```
You have an error in your SQL syntax; check the manual that corresponds
to your MySQL server version for the right syntax to use near 'integer'
```
Rather than casting to `integer`, we should be casting to `unsigned`
or calling `floor(..)`.
> Fix syntax error near `integer`, and value NIL 

- src/sources/mssql/mssql-schema.lisp
It solves https://github.com/dimitri/pgloader/issues/1144
> Keep name casing for foreign keys on mssql

- src/sources/mysql/mysql-cast-rules.lisp
Fixes dimitri/pgloader#1186
Please comment if you think `(:source (:type "int" :unsigned t)` should be `(:source (:type "int" :unsigned t :auto-increment nil)` instead, and I can fix it.
However, the current version passed all tests I did with ints.
> Add MySQL unsigned int casting rules

- src/sources/mysql/mysql.lisp
I tried to load MySQL tables into PostgreSQL with `rows per range` option. The following is full `with` options.
```
WITH workers = 8, concurrency = 2, multiple readers per thread, rows per range = 50000, batch rows = 10000, prefetch rows = 10000
```
But at some tables, the last record was not copied to PostgreSQL.
where clause for ranged load seems to ignore the last record (or the record has max primary key).
https://github.com/dimitri/pgloader/blob/9788cc64ee8014f670e0d34c853b86c82693c9ec/src/sources/mysql/mysql.lisp#L120
Thank you for checking my pull request.
> Fix ranged load from MySQL does not load the last record.

- docs/index.rst
The header "On error stop / On error resume next" contains some text that should be in the paragraph instead.
>   Fix the header "On error stop / On error resume next"

- pgloader.spec
This works around a bug introduced by `cl+ssl-20211020-git.tgz` and "fixes" #1338
Unfortunately we have to make `openssl-devel` a runtime dependency to get around this bug. I think I would be preferable to use a version of cl+ssl which would be happy with `libcrypto.so.10`
> Add openssl-devel dependency to pgloader.spec

- docs/ref/mssql.rst
While 
>When loading from a `MS SQL` database, the same options as when loading a `MS SQL` database are supported
is certainly true, it does not really tell me much ;)
> Fixes typo in MS SQL Migration Options docs

- src/hooks.lisp
cl+ssl::libcrypto is also read at startup. If not properly closed in the
hooks, together with libssl, libcrypto will be loaded at startup and if
the first cl+ssl file alternative fails, the debugger is invoked.
* Fixes #1370
> Force libcrypto reload in src/hooks.lisp

- src/parsers/command-cast-rules.lisp
Underscores might exist in cast type names, for example if the type being cast is an enum (which can have arbitrary names).
Fixes #1378
> Allow underscores in cast type names

- Dockerfile
- Dockerfile.ccl
This just makes it easier to customise the build without having to fork. `DYNSIZE` is probably one of the most used parameters here that people want to easily change.
> parameterize DYNSIZE in dockerfiles

- src/utils/charsets.lisp
The internal represtation of the SBCL *external-formats* has changed to a
new structure which is not an hash-table anymore.
> Fix looping over sbcl *external-formats*.

- docs/ref/csv.rst
CSV Source Specification: From
One of special values are `FILENAME MATCHING` and not `FILENAMES MATCHING`
> Fix documentation typo: FILENAMES MATCHING

- src/api.lisp
- src/main.lisp
The compile function returns warnings-p and failure-p values, use that to
decide if the code could be compiled, and only signal a condition when it
has been fatal to compiling the code at run-time.
The SBCL compiler is getting smarter at removing unreachable code, and it
looks like pgloader is producing some unreachable code from parsing the user
provided commands.
Fixes #1407
> SBCL compiler notes should not be fatal to pgloader.

- src/utils/queries.lisp
The way we manage and then fetch the SQL queries embedded in the pgloader
binary we should really take the unix-namestring rather than the
native-namestring. Of course, this only matters when the host OS is NOT
unix, which is why this bug existed for so long.
Fixes #1418.
> Use the unix-namestring as the hash key for SQL queries.

- src/pgsql/pgsql-create-schema.lisp
When a sequence is defined with a minimum value, and the sequence to migrate is empty, the setval fails due to 1 being the default (which may be lower than the defined minimum value)
> Added support for sequences with minvalue defined

- src/sources/mysql/mysql-cast-rules.lisp
This is fix for #1248 
where is missing default cast for signed int without precision to serial in mysql
examples with problem are in that issue
it's coded by blind; i don't tested or compiled it
> Fix mapping mysql signed int with auto_incement to postgresql serial (#1248)

- Dockerfile
- Dockerfile.ccl
Building Docker container broke after Debian Bookwork release. This PR fixes the issue and pins Dockerfile to use Bookworm so that it doesn't break after next release.
> Fix Dockerfile build after new Debian release

- Dockerfile
Currently, we install ca-certificates package only on the builder, not on the docker image which is distributed to the user. Without CA certificates, we see errors like below,
```
2024-09-18T05:30:46.112001Z ERROR Connecting to PostgreSQL <host name>: SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
DB-CONNECTION-ERROR: Failed to connect to pgsql at "<host name>" (port 30025) as user "tsdbadmin": SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
An unhandled error condition has been signalled:
Failed to connect to pgsql at "<host name>" (port 30025) as user "tsdbadmin": SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```
> Install CA certificates on docker image
